language: node_js
sudo: required
node_js:
  - 10.10.0
before_script:
  - npm install vue vue-template-compiler
script:
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then cp ./scripts/.npmrc.template $HOME/.npmrc; fi
  - COVERAGE=true npm run test
  - npm run codecov
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then npm run pub-with-ci; fi
  - bash ./scripts/deploy-to-gh-pages.sh
